In [118]:
import pandas as pd

In [119]:
df = pd.read_csv("../../data_fetching/truthSocial/trump_tweets.csv")
df.head()

,url,username,DateKey,TimeKey,Text,deleted
0,https://trumpstruth.org/statuses/37757,realDonaldTrump,20260414,140900,"Bruce Blakeman, the highly respected and very ...",0
1,https://trumpstruth.org/statuses/37756,realDonaldTrump,20260414,135100,"Alan, one of the greats, should do it! Preside...",0
2,https://trumpstruth.org/statuses/37755,realDonaldTrump,20260414,134900,Biden administration weaponized law to infring...,0
3,https://trumpstruth.org/statuses/37753,realDonaldTrump,20260414,52400,Georgia lawmaker wants Fani Willis to answer q...,0
4,https://trumpstruth.org/statuses/37754,realDonaldTrump,20260414,52300,Alan Dershowitz: Trump could move to expunge 2...,0

In [120]:
print(df.info())
print(len(df))

<class 'pandas.DataFrame'>
RangeIndex: 30851 entries, 0 to 30850
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   url       30851 non-null  str
 1   username  30851 non-null  str
 2   DateKey   30851 non-null  int64
 3   TimeKey   30851 non-null  int64
 4   Text      25542 non-null  str
 5   deleted   30851 non-null  int64
dtypes: int64(3), str(3)
memory usage: 1.4 MB
None
30851

### removing deleted tweets (deleted = 1)

In [121]:
df = df[df['deleted'] == 0]

In [122]:
len(df)

30263

#### we hebben tweets die geen text hebben, deze verwijderen we ook

In [123]:
df = df[df['Text'].notna()]
print(len(df))

24983

In [124]:
df.head()

,url,username,DateKey,TimeKey,Text,deleted
0,https://trumpstruth.org/statuses/37757,realDonaldTrump,20260414,140900,"Bruce Blakeman, the highly respected and very ...",0
1,https://trumpstruth.org/statuses/37756,realDonaldTrump,20260414,135100,"Alan, one of the greats, should do it! Preside...",0
2,https://trumpstruth.org/statuses/37755,realDonaldTrump,20260414,134900,Biden administration weaponized law to infring...,0
3,https://trumpstruth.org/statuses/37753,realDonaldTrump,20260414,52400,Georgia lawmaker wants Fani Willis to answer q...,0
4,https://trumpstruth.org/statuses/37754,realDonaldTrump,20260414,52300,Alan Dershowitz: Trump could move to expunge 2...,0

In [125]:
df.to_csv("../../processed/trump_tweets.csv", index=False)